### ISSUE TITLE
Add sources

### ISSUE THREAD

**Issue by john-shaffer** [insilica/rs-srvc#9]
1. Add a sources section to sr.yaml. This turns an sr.yaml like
```yaml
flows:
  import:
    steps:
      - run-embedded: generator https://pubmed-http-server.fly.dev?q=susceptibility+factor

  recogito:
    steps:
      - run-embedded: generator sink.jsonl

      - run-embedded: html https://static.sysrev.com/srvc/recogito/
        labels: [annotation]

  brat:
    steps:
      - run-embedded: generator sink.jsonl

      - run-embedded: html https://static.sysrev.com/srvc/brat/
        labels: [annotation]
```

into

```yaml
sources: https://pubmed-http-server.fly.dev?q=susceptibility+factor

flows:
  recogito:
    steps:
      - run-embedded: html https://static.sysrev.com/srvc/recogito/
        labels: [annotation]

  brat:
    steps:
      - run-embedded: html https://static.sysrev.com/srvc/brat/
        labels: [annotation]
```
2. Add `source` and `event-to-source` events that record which events came from which sources.
3. Add `source-import-complete` event that records Last-Modified and ETag headers.

This lets us efficiently check for updates automatically and efficiently. The current process involves either importing events on every run, which can be slow, or manually running an import flow.

This would make #4 irrelevant.
